In [ ]:
!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
!tar -xzvf ta-lib-0.4.0-src.tar.gz
%cd ta-lib
!./configure --prefix=/usr
!make
!make install
!pip install Ta-Lib
import talib

In [5]:
import talib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

In [152]:
ticker = yf.Ticker("RELIANCE.NS")
df = ticker.history(period='5y',interval='1d')
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2018-08-06 00:00:00+05:30,1147.735968,1166.560908,1146.419240,1163.244629,4054489,0.0,0.0
2018-08-07 00:00:00+05:30,1165.487851,1171.827854,1148.028441,1155.051147,4097939,0.0,0.0
2018-08-08 00:00:00+05:30,1155.831586,1192.408610,1155.831586,1187.726685,7987438,0.0,0.0
2018-08-09 00:00:00+05:30,1191.433256,1201.382213,1182.167123,1187.970581,6911830,0.0,0.0
2018-08-10 00:00:00+05:30,1181.191517,1185.093141,1172.705685,1174.558960,3615156,0.0,0.0
...,...,...,...,...,...,...,...
2023-07-31 00:00:00+05:30,2527.850098,2553.899902,2517.949951,2549.250000,4275587,0.0,0.0
2023-08-01 00:00:00+05:30,2555.000000,2559.000000,2505.300049,2513.199951,4768316,0.0,0.0
2023-08-02 00:00:00+05:30,2509.199951,2512.000000,2463.600098,2486.350098,6374107,0.0,0.0
2023-08-03 00:00:00+05:30,2475.300049,2500.899902,2458.050049,2475.899902,5084175,0.0,0.0
2023-08-04 00:00:00+05:30,2498.800049,2516.000000,2471.600098,2509.550049,11442805,0.0,0.0

In [153]:
df = df.reset_index(drop=True)

In [154]:
df = df.drop(["Dividends", "Stock Splits"], axis=1)

In [155]:
df

             Open         High          Low        Close    Volume
0     1147.735968  1166.560908  1146.419240  1163.244629   4054489
1     1165.487851  1171.827854  1148.028441  1155.051147   4097939
2     1155.831586  1192.408610  1155.831586  1187.726685   7987438
3     1191.433256  1201.382213  1182.167123  1187.970581   6911830
4     1181.191517  1185.093141  1172.705685  1174.558960   3615156
...           ...          ...          ...          ...       ...
1229  2527.850098  2553.899902  2517.949951  2549.250000   4275587
1230  2555.000000  2559.000000  2505.300049  2513.199951   4768316
1231  2509.199951  2512.000000  2463.600098  2486.350098   6374107
1232  2475.300049  2500.899902  2458.050049  2475.899902   5084175
1233  2498.800049  2516.000000  2471.600098  2509.550049  11442805

[1234 rows x 5 columns]

In [156]:
data = np.array([df['Open'], df['High'], df['Low'], df['Close']])

In [157]:
data.shape

(4, 1234)

In [158]:
ema50 = talib.EMA(data[3], 50)

In [159]:
df['ema50'] = pd.DataFrame(ema50)

In [160]:
df

,Open,High,Low,Close,Volume,ema50
0,1147.735968,1166.560908,1146.419240,1163.244629,4054489,NaN
1,1165.487851,1171.827854,1148.028441,1155.051147,4097939,NaN
2,1155.831586,1192.408610,1155.831586,1187.726685,7987438,NaN
3,1191.433256,1201.382213,1182.167123,1187.970581,6911830,NaN
4,1181.191517,1185.093141,1172.705685,1174.558960,3615156,NaN
...,...,...,...,...,...,...
1229,2527.850098,2553.899902,2517.949951,2549.250000,4275587,2563.665548
1230,2555.000000,2559.000000,2505.300049,2513.199951,4768316,2561.686505
1231,2509.199951,2512.000000,2463.600098,2486.350098,6374107,2558.732136
1232,2475.300049,2500.899902,2458.050049,2475.899902,5084175,2555.483813
1233,2498.800049,2516.000000,2471.600098,2509.550049,11442805,2553.682489

In [161]:
df.tail(1)

             Open    High          Low        Close    Volume        ema50
1233  2498.800049  2516.0  2471.600098  2509.550049  11442805  2553.682489

In [162]:
last = np.array(df.tail(1))
last[0][5]

2553.682488767164

In [163]:
if (last[0][3] > last[0][5]) & (last[0][3] < last[0][5] + (last[0][5]*0.03)):
  print("BUY")
else:
  print("Not Now")

Not Now

In [164]:
def function(tick):
  ticker = yf.Ticker(tick)
  df = ticker.history(period='5y',interval='1d')
  df = df.reset_index(drop=True)
  df = df[["Open", "High", "Low", "Close"]]
  data = np.array([df['Open'], df['High'], df['Low'], df['Close']])
  ema50 = talib.EMA(data[3], 50)
  df['ema50'] = pd.DataFrame(ema50)
  last = np.array(df.tail(1))
  if ((last[0][3] > last[0][4]) and (last[0][3] < last[0][4] - (last[0][4]*0.04))) or ((last[0][3] < last[0][4]) and (last[0][3] > last[0][4] + (last[0][4]*0.04))):
  # if (last[0][3] < (last[0][5] + (last[0][5]*0.04))) or (last[0][3] > (last[0][5] - (last[0][5]*0.04))):
    return True
  else:
    return False

In [165]:
tick = ["LEMONTREE.NS", "RENUKA.NS", "HINDZINC.NS", "RVNL.NS", "ABB.NS", "MASTEK.NS", "JUBLPHARMA.NS", "ATUL.NS", "BSE.NS"]
# tick

df1 = pd.read_excel("/content/EQ.xlsx")
ticks = list(df1['20MICRONS'])
# print(ticks)
buy = []
no = []
ticks.remove("BROOKS-RE")
ticks.remove("VCL-RE")
for i in ticks[:100]:
  print(i+".NS")
  if (function(i + ".NS")):
    buy.append(i)
  else:
    no.append(i)

21STCENMGM.NS
360ONE.NS
3IINFOLTD.NS
3MINDIA.NS
3PLAND.NS
5PAISA.NS
63MOONS.NS
A2ZINFRA.NS
AAATECH.NS
AAKASH.NS
AAREYDRUGS.NS
AARON.NS
AARTECH.NS
AARTIDRUGS.NS
AARTIIND.NS
AARTIPHARM.NS
AARTISURF.NS
AARVEEDEN.NS
AARVI.NS
AAVAS.NS
ABAN.NS
ABB.NS
ABBOTINDIA.NS
ABCAPITAL.NS
ABFRL.NS
ABMINTLLTD.NS
ABSLAMC.NS
ACC.NS
ACCELYA.NS
ACCURACY.NS
ACE.NS
ACEINTEG.NS
ACI.NS
ACL.NS
ADANIENT.NS
ADANIGREEN.NS
ADANIPORTS.NS
ADANIPOWER.NS
ADANITRANS.NS
ADFFOODS.NS
ADL.NS
ADORWELD.NS
ADROITINFO.NS
ADSL.NS
ADVANIHOTR.NS
ADVENZYMES.NS
AEGISCHEM.NS
AETHER.NS
AFFLE.NS
AGARIND.NS
AGI.NS
AGRITECH.NS
AGROPHOS.NS
AGSTRA.NS
AHL.NS
AHLADA.NS
AHLEAST.NS
AHLUCONT.NS
AIAENG.NS
AIRAN.NS
AIROLAM.NS
AJANTPHARM.NS
AJMERA.NS
AJOONI.NS
AKASH.NS
AKG.NS
AKI.NS
AKSHAR.NS
AKSHARCHEM.NS
AKSHOPTFBR.NS
AKZOINDIA.NS
ALANKIT.NS
ALBERTDAVD.NS
ALEMBICLTD.NS
ALICON.NS
ALKALI.NS
ALKEM.NS
ALKYLAMINE.NS
ALLCARGO.NS
ALLSEC.NS
ALMONDZ.NS
ALOKINDS.NS
ALPA.NS
ALPHAGEO.NS
ALPSINDUS.NS
AMARAJABAT.NS
AMBER.NS
AMBICAAGAR.NS
AMBIKCO.NS
AMBUJACEM.NS
AMDIND.NS
AMIORG.NS
AMJLAND.NS
AMRUTANJAN.NS
ANANDRATHI.NS
ANANTRAJ.NS
ANDHRAPAP.NS
ANDHRSUGAR.NS
ANDREWYU.NS
ANGELONE.NS

In [110]:
buy

[]

In [111]:
no

['21STCENMGM',
 '360ONE',
 '3IINFOLTD',
 '3MINDIA',
 '3PLAND',
 '5PAISA',
 '63MOONS',
 'A2ZINFRA',
 'AAATECH',
 'AAKASH',
 'AAREYDRUGS',
 'AARON',
 'AARTECH',
 'AARTIDRUGS',
 'AARTIIND',
 'AARTIPHARM',
 'AARTISURF',
 'AARVEEDEN',
 'AARVI',
 'AAVAS',
 'ABAN',
 'ABB',
 'ABBOTINDIA',
 'ABCAPITAL',
 'ABFRL',
 'ABMINTLLTD',
 'ABSLAMC',
 'ACC',
 'ACCELYA',
 'ACCURACY',
 'ACE',
 'ACEINTEG',
 'ACI',
 'ACL',
 'ADANIENT',
 'ADANIGREEN',
 'ADANIPORTS',
 'ADANIPOWER',
 'ADANITRANS',
 'ADFFOODS',
 'ADL',
 'ADORWELD',
 'ADROITINFO',
 'ADSL',
 'ADVANIHOTR',
 'ADVENZYMES',
 'AEGISCHEM',
 'AETHER',
 'AFFLE',
 'AGARIND',
 'AGI',
 'AGRITECH',
 'AGROPHOS',
 'AGSTRA',
 'AHL',
 'AHLADA',
 'AHLEAST',
 'AHLUCONT',
 'AIAENG',
 'AIRAN',
 'AIROLAM',
 'AJANTPHARM',
 'AJMERA',
 'AJOONI',
 'AKASH',
 'AKG',
 'AKI',
 'AKSHAR',
 'AKSHARCHEM',
 'AKSHOPTFBR',
 'AKZOINDIA',
 'ALANKIT',
 'ALBERTDAVD',
 'ALEMBICLTD',
 'ALICON',
 'ALKALI',
 'ALKEM',
 'ALKYLAMINE',
 'ALLCARGO',
 'ALLSEC',
 'ALMONDZ',
 'ALOKINDS',
 'ALPA',
 'ALPHAGEO',
 'ALPSINDUS',
 'AMARAJABAT',
 'AMBER',
 'AMBICAAGAR',
 'AMBIKCO',
 'AMBUJACEM',
 'AMDIND',
 'AMIORG',
 'AMJLAND',
 'AMRUTANJAN',
 'ANANDRATHI',
 'ANANTRAJ',
 'ANDHRAPAP',
 'ANDHRSUGAR',
 'ANDREWYU',
 'ANGELONE']

In [38]:
!pip install plyer

Collecting plyer
  Downloading plyer-2.1.0-py2.py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.3/142.3 kB 3.7 MB/s eta 0:00:00
Installing collected packages: plyer
Successfully installed plyer-2.1.0

In [39]:
import yfinance as yf
import numpy as np
from plyer import notification
import time

def calculate_ema(data, window):
    return data['Close'].ewm(span=window, adjust=False).mean()

def check_ema_retest(stock_symbol, ema_window, retest_window):
    stock_data = yf.download(stock_symbol, period="1d", interval="5m")
    if len(stock_data) < ema_window + retest_window:
        return False

    ema = calculate_ema(stock_data, ema_window)
    latest_close = stock_data['Close'][-1]
    ema_current = ema[-1]

    if latest_close > ema_current:
        retest_prices = stock_data['Low'][-retest_window:]
        if np.any(retest_prices < ema_current):
            print("YES")

def main():
    stock_symbol = "AAPL"  # Change this to your desired stock symbol
    ema_window = 20
    retest_window = 3

    while True:
        if check_ema_retest(stock_symbol, ema_window, retest_window):
            notification_title = "EMA Retest Buy Notification"
            notification_message = f"{stock_symbol} has retested EMA-{ema_window} and might be a good time to buy."
            notification.notify(title=notification_title, message=notification_message)
        time.sleep(300)  # Wait for 5 minutes before checking again

if __name__ == "__main__":
    main()

[*********************100%***********************]  1 of 1 completed

KeyboardInterrupt: ignored